import 'package:flutter/material.dart';
import 'package:my_app/login_screen.dart';
import 'package:my_app/utils/app_api.dart';
import 'package:shared_preferences/shared_preferences.dart';

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState() => _HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> {
  bool _isLoading = true; String _username = ''; Map<String, dynamic> _summary = {'balance': 0, 'total_deposit': 0, 'total_withdrawal': 0, 'transaction_count': 0};
  @override void initState() { super.initState(); _loadDashboard(); }
  Future<void> _loadDashboard() async { final preferences = await SharedPreferences.getInstance(); _username = preferences.getString('username') ?? 'ผู้ใช้'; try { final result = await AppApi.getAuthenticated('/dashboard/summary'); if (result['isError'] != true) _summary = result['data'] as Map<String, dynamic>; } catch (_) {} if (mounted) setState(() => _isLoading = false); }
  Future<void> _logout() async { final preferences = await SharedPreferences.getInstance(); await preferences.clear(); if (!mounted) return; Navigator.of(context).pushAndRemoveUntil(MaterialPageRoute(builder: (_) => const LoginScreen()), (_) => false); }
  String _money(dynamic value) => '฿${((value as num?)?.toDouble() ?? 0).toStringAsFixed(2)}';
  Widget _statCard(String title, String value, IconData icon, Color color) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Icon(icon, color: color), const SizedBox(height: 12), Text(title, style: TextStyle(color: Colors.grey.shade700)), const SizedBox(height: 4), Text(value, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 17))])));
  @override Widget build(BuildContext context) => Scaffold(appBar: AppBar(title: const Text('หน้าหลัก'), actions: [IconButton(onPressed: _logout, icon: const Icon(Icons.logout), tooltip: 'ออกจากระบบ')]), body: RefreshIndicator(onRefresh: _loadDashboard, child: _isLoading ? const Center(child: CircularProgressIndicator()) : ListView(padding: const EdgeInsets.all(20), children: [Text('สวัสดี, $_username', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 6), Text('ภาพรวมบัญชีเงินฝากของคุณ', style: TextStyle(color: Colors.grey.shade700)), const SizedBox(height: 24), Card(color: const Color(0xFF00695C), child: Padding(padding: const EdgeInsets.all(24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('ยอดเงินคงเหลือปัจจุบัน', style: TextStyle(color: Colors.white70)), const SizedBox(height: 8), Text(_money(_summary['balance']), style: const TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold))]))), const SizedBox(height: 16), Row(children: [Expanded(child: _statCard('ยอดฝากรวม', _money(_summary['total_deposit']), Icons.south_west, Colors.green)), const SizedBox(width: 12), Expanded(child: _statCard('ยอดถอนรวม', _money(_summary['total_withdrawal']), Icons.north_east, Colors.red))]), const SizedBox(height: 12), _statCard('จำนวนรายการฝาก-ถอน', '${_summary['transaction_count'] ?? 0} รายการ', Icons.receipt_long_outlined, Colors.blue), const SizedBox(height: 28), Text('รายการล่าสุด', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 10), const Card(child: ListTile(leading: Icon(Icons.info_outline), title: Text('ยังไม่มีรายการธุรกรรม'), subtitle: Text('ส่วนเพิ่มรายการฝาก-ถอนจะดำเนินการในลำดับถัดไป')))])));
}
